openapi: 3.0.3
info:
  title: STD23098 - TD3
  version: '1.0.2'
servers:
  - url: https://localhost.std23098.com
paths:
  /meals:
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          required: true
        - in: query
          name: pageSize
          schema:
            type: integer
          required: true
      responses:
        200:
          description: List of meals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Meal'
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                  format: decimal
        required: true
      responses:
        201:
          description: Created meal
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Meal'
    put:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                name:
                  type: string
                price:
                  type: number
                  format: decimal
        required: true
      responses:
        200:
          description: Updated meal
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Meal'
    delete:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
        required: true
      responses:
        200:
          description: Deleted meal
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Meal'
components:
  schemas:
    Meal:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        price:
          type: number
          format: decimal
